name: Slack

on:
  push:
    branches: [ master ]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
   
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C04GHR8K99S
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: xoxb-1084467806503-4561792758742-A9E80gw2QhHmCsjPGmIyOfJp
